// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/api/appproto/headers.proto

package appproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Network_TYPE int32

const (
	Network_NT_UNKNOWN Network_TYPE = 0
	Network_WIFI       Network_TYPE = 1
	Network_CELLULAR   Network_TYPE = 2
	Network_OFFLINE    Network_TYPE = 3
	Network_OTHERNET   Network_TYPE = 4
	Network_ETHERNET   Network_TYPE = 5
)

// Enum value maps for Network_TYPE.
var (
	Network_TYPE_name = map[int32]string{
		0: "NT_UNKNOWN",
		1: "WIFI",
		2: "CELLULAR",
		3: "OFFLINE",
		4: "OTHERNET",
		5: "ETHERNET",
	}
	Network_TYPE_value = map[string]int32{
		"NT_UNKNOWN": 0,
		"WIFI":       1,
		"CELLULAR":   2,
		"OFFLINE":    3,
		"OTHERNET":   4,
		"ETHERNET":   5,
	}
)

func (x Network_TYPE) Enum() *Network_TYPE {
	p := new(Network_TYPE)
	*p = x
	return p
}

func (x Network_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_appproto_headers_proto_enumTypes[0].Descriptor()
}

func (Network_TYPE) Type() protoreflect.EnumType {
	return &file_internal_api_appproto_headers_proto_enumTypes[0]
}

func (x Network_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Network_TYPE.Descriptor instead.
func (Network_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{2, 0}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int32                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Build         int32                  `protobuf:"varint,2,opt,name=build,proto3" json:"build,omitempty"`
	Buvid         string                 `protobuf:"bytes,3,opt,name=buvid,proto3" json:"buvid,omitempty"`
	MobiApp       string                 `protobuf:"bytes,4,opt,name=mobi_app,json=mobiApp,proto3" json:"mobi_app,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Device        string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Channel       string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Brand         string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	Osver         string                 `protobuf:"bytes,10,opt,name=osver,proto3" json:"osver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_internal_api_appproto_headers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_headers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Device) GetBuild() int32 {
	if x != nil {
		return x.Build
	}
	return 0
}

func (x *Device) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

func (x *Device) GetMobiApp() string {
	if x != nil {
		return x.MobiApp
	}
	return ""
}

func (x *Device) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Device) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Device) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Device) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetOsver() string {
	if x != nil {
		return x.Osver
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	MobiApp       string                 `protobuf:"bytes,2,opt,name=mobi_app,json=mobiApp,proto3" json:"mobi_app,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Build         int32                  `protobuf:"varint,4,opt,name=build,proto3" json:"build,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Buvid         string                 `protobuf:"bytes,6,opt,name=buvid,proto3" json:"buvid,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_internal_api_appproto_headers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_headers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Metadata) GetMobiApp() string {
	if x != nil {
		return x.MobiApp
	}
	return ""
}

func (x *Metadata) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Metadata) GetBuild() int32 {
	if x != nil {
		return x.Build
	}
	return 0
}

func (x *Metadata) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Metadata) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

func (x *Metadata) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Network_TYPE           `protobuf:"varint,1,opt,name=type,proto3,enum=appproto.Network_TYPE" json:"type,omitempty"`
	Oid           string                 `protobuf:"bytes,3,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_internal_api_appproto_headers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_headers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{2}
}

func (x *Network) GetType() Network_TYPE {
	if x != nil {
		return x.Type
	}
	return Network_NT_UNKNOWN
}

func (x *Network) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type Locale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CLocale       *Locale_LocaleIds      `protobuf:"bytes,1,opt,name=c_locale,json=cLocale,proto3" json:"c_locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale) Reset() {
	*x = Locale{}
	mi := &file_internal_api_appproto_headers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_headers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{3}
}

func (x *Locale) GetCLocale() *Locale_LocaleIds {
	if x != nil {
		return x.CLocale
	}
	return nil
}

type FawkesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appkey        string                 `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FawkesReq) Reset() {
	*x = FawkesReq{}
	mi := &file_internal_api_appproto_headers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FawkesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FawkesReq) ProtoMessage() {}

func (x *FawkesReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_headers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FawkesReq.ProtoReflect.Descriptor instead.
func (*FawkesReq) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{4}
}

func (x *FawkesReq) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *FawkesReq) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *FawkesReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Locale_LocaleIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale_LocaleIds) Reset() {
	*x = Locale_LocaleIds{}
	mi := &file_internal_api_appproto_headers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale_LocaleIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale_LocaleIds) ProtoMessage() {}

func (x *Locale_LocaleIds) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_headers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale_LocaleIds.ProtoReflect.Descriptor instead.
func (*Locale_LocaleIds) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_headers_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Locale_LocaleIds) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Locale_LocaleIds) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_internal_api_appproto_headers_proto protoreflect.FileDescriptor

const file_internal_api_appproto_headers_proto_rawDesc = "" +
	"\n" +
	"#internal/api/appproto/headers.proto\x12\bappproto\"\xf6\x01\n" +
	"\x06Device\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12\x14\n" +
	"\x05build\x18\x02 \x01(\x05R\x05build\x12\x14\n" +
	"\x05buvid\x18\x03 \x01(\tR\x05buvid\x12\x19\n" +
	"\bmobi_app\x18\x04 \x01(\tR\amobiApp\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12\x14\n" +
	"\x05osver\x18\n" +
	" \x01(\tR\x05osver\"\xbe\x01\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x19\n" +
	"\bmobi_app\x18\x02 \x01(\tR\amobiApp\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x14\n" +
	"\x05build\x18\x04 \x01(\x05R\x05build\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x14\n" +
	"\x05buvid\x18\x06 \x01(\tR\x05buvid\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\"\xa0\x01\n" +
	"\aNetwork\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.appproto.Network.TYPER\x04type\x12\x10\n" +
	"\x03oid\x18\x03 \x01(\tR\x03oid\"W\n" +
	"\x04TYPE\x12\x0e\n" +
	"\n" +
	"NT_UNKNOWN\x10\x00\x12\b\n" +
	"\x04WIFI\x10\x01\x12\f\n" +
	"\bCELLULAR\x10\x02\x12\v\n" +
	"\aOFFLINE\x10\x03\x12\f\n" +
	"\bOTHERNET\x10\x04\x12\f\n" +
	"\bETHERNET\x10\x05\"\x80\x01\n" +
	"\x06Locale\x125\n" +
	"\bc_locale\x18\x01 \x01(\v2\x1a.appproto.Locale.LocaleIdsR\acLocale\x1a?\n" +
	"\tLocaleIds\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"T\n" +
	"\tFawkesReq\x12\x16\n" +
	"\x06appkey\x18\x01 \x01(\tR\x06appkey\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionIdB;Z9github.com/charleszheng44/bbdown-go/internal/api/appprotob\x06proto3"

var (
	file_internal_api_appproto_headers_proto_rawDescOnce sync.Once
	file_internal_api_appproto_headers_proto_rawDescData []byte
)

func file_internal_api_appproto_headers_proto_rawDescGZIP() []byte {
	file_internal_api_appproto_headers_proto_rawDescOnce.Do(func() {
		file_internal_api_appproto_headers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_appproto_headers_proto_rawDesc), len(file_internal_api_appproto_headers_proto_rawDesc)))
	})
	return file_internal_api_appproto_headers_proto_rawDescData
}

var file_internal_api_appproto_headers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_api_appproto_headers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_api_appproto_headers_proto_goTypes = []any{
	(Network_TYPE)(0),        // 0: appproto.Network.TYPE
	(*Device)(nil),           // 1: appproto.Device
	(*Metadata)(nil),         // 2: appproto.Metadata
	(*Network)(nil),          // 3: appproto.Network
	(*Locale)(nil),           // 4: appproto.Locale
	(*FawkesReq)(nil),        // 5: appproto.FawkesReq
	(*Locale_LocaleIds)(nil), // 6: appproto.Locale.LocaleIds
}
var file_internal_api_appproto_headers_proto_depIdxs = []int32{
	0, // 0: appproto.Network.type:type_name -> appproto.Network.TYPE
	6, // 1: appproto.Locale.c_locale:type_name -> appproto.Locale.LocaleIds
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_appproto_headers_proto_init() }
func file_internal_api_appproto_headers_proto_init() {
	if File_internal_api_appproto_headers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_appproto_headers_proto_rawDesc), len(file_internal_api_appproto_headers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_appproto_headers_proto_goTypes,
		DependencyIndexes: file_internal_api_appproto_headers_proto_depIdxs,
		EnumInfos:         file_internal_api_appproto_headers_proto_enumTypes,
		MessageInfos:      file_internal_api_appproto_headers_proto_msgTypes,
	}.Build()
	File_internal_api_appproto_headers_proto = out.File
	file_internal_api_appproto_headers_proto_goTypes = nil
	file_internal_api_appproto_headers_proto_depIdxs = nil
}
