// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/api/appproto/playviewreply.proto

package appproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayViewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoInfo     *VideoInfo             `protobuf:"bytes,1,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayViewReply) Reset() {
	*x = PlayViewReply{}
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayViewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayViewReply) ProtoMessage() {}

func (x *PlayViewReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayViewReply.ProtoReflect.Descriptor instead.
func (*PlayViewReply) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_playviewreply_proto_rawDescGZIP(), []int{0}
}

func (x *PlayViewReply) GetVideoInfo() *VideoInfo {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       uint32                 `protobuf:"varint,1,opt,name=quality,proto3" json:"quality,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Timelength    uint64                 `protobuf:"varint,3,opt,name=timelength,proto3" json:"timelength,omitempty"`
	VideoCodecid  uint32                 `protobuf:"varint,4,opt,name=video_codecid,json=videoCodecid,proto3" json:"video_codecid,omitempty"`
	StreamList    []*StreamItem          `protobuf:"bytes,5,rep,name=stream_list,json=streamList,proto3" json:"stream_list,omitempty"`
	DashAudio     []*DashItem            `protobuf:"bytes,6,rep,name=dash_audio,json=dashAudio,proto3" json:"dash_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_playviewreply_proto_rawDescGZIP(), []int{1}
}

func (x *VideoInfo) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *VideoInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *VideoInfo) GetTimelength() uint64 {
	if x != nil {
		return x.Timelength
	}
	return 0
}

func (x *VideoInfo) GetVideoCodecid() uint32 {
	if x != nil {
		return x.VideoCodecid
	}
	return 0
}

func (x *VideoInfo) GetStreamList() []*StreamItem {
	if x != nil {
		return x.StreamList
	}
	return nil
}

func (x *VideoInfo) GetDashAudio() []*DashItem {
	if x != nil {
		return x.DashAudio
	}
	return nil
}

type StreamItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamInfo    *StreamInfo            `protobuf:"bytes,1,opt,name=stream_info,json=streamInfo,proto3" json:"stream_info,omitempty"`
	DashVideo     *DashVideo             `protobuf:"bytes,2,opt,name=dash_video,json=dashVideo,proto3" json:"dash_video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamItem) Reset() {
	*x = StreamItem{}
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamItem) ProtoMessage() {}

func (x *StreamItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamItem.ProtoReflect.Descriptor instead.
func (*StreamItem) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_playviewreply_proto_rawDescGZIP(), []int{2}
}

func (x *StreamItem) GetStreamInfo() *StreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

func (x *StreamItem) GetDashVideo() *DashVideo {
	if x != nil {
		return x.DashVideo
	}
	return nil
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       uint32                 `protobuf:"varint,1,opt,name=quality,proto3" json:"quality,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ErrCode       uint32                 `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_playviewreply_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInfo) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *StreamInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *StreamInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StreamInfo) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

type DashVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	BackupUrl     []string               `protobuf:"bytes,2,rep,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	Bandwidth     uint32                 `protobuf:"varint,3,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Codecid       uint32                 `protobuf:"varint,4,opt,name=codecid,proto3" json:"codecid,omitempty"`
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashVideo) Reset() {
	*x = DashVideo{}
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashVideo) ProtoMessage() {}

func (x *DashVideo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashVideo.ProtoReflect.Descriptor instead.
func (*DashVideo) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_playviewreply_proto_rawDescGZIP(), []int{4}
}

func (x *DashVideo) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *DashVideo) GetBackupUrl() []string {
	if x != nil {
		return x.BackupUrl
	}
	return nil
}

func (x *DashVideo) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *DashVideo) GetCodecid() uint32 {
	if x != nil {
		return x.Codecid
	}
	return 0
}

func (x *DashVideo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *DashVideo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DashItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	BackupUrl     []string               `protobuf:"bytes,3,rep,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	Bandwidth     uint32                 `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Codecid       uint32                 `protobuf:"varint,5,opt,name=codecid,proto3" json:"codecid,omitempty"`
	Md5           string                 `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5,omitempty"`
	Size          uint64                 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashItem) Reset() {
	*x = DashItem{}
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashItem) ProtoMessage() {}

func (x *DashItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_appproto_playviewreply_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashItem.ProtoReflect.Descriptor instead.
func (*DashItem) Descriptor() ([]byte, []int) {
	return file_internal_api_appproto_playviewreply_proto_rawDescGZIP(), []int{5}
}

func (x *DashItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DashItem) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *DashItem) GetBackupUrl() []string {
	if x != nil {
		return x.BackupUrl
	}
	return nil
}

func (x *DashItem) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *DashItem) GetCodecid() uint32 {
	if x != nil {
		return x.Codecid
	}
	return 0
}

func (x *DashItem) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *DashItem) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_internal_api_appproto_playviewreply_proto protoreflect.FileDescriptor

const file_internal_api_appproto_playviewreply_proto_rawDesc = "" +
	"\n" +
	")internal/api/appproto/playviewreply.proto\x12\bappproto\"C\n" +
	"\rPlayViewReply\x122\n" +
	"\n" +
	"video_info\x18\x01 \x01(\v2\x13.appproto.VideoInfoR\tvideoInfo\"\xec\x01\n" +
	"\tVideoInfo\x12\x18\n" +
	"\aquality\x18\x01 \x01(\rR\aquality\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"timelength\x18\x03 \x01(\x04R\n" +
	"timelength\x12#\n" +
	"\rvideo_codecid\x18\x04 \x01(\rR\fvideoCodecid\x125\n" +
	"\vstream_list\x18\x05 \x03(\v2\x14.appproto.StreamItemR\n" +
	"streamList\x121\n" +
	"\n" +
	"dash_audio\x18\x06 \x03(\v2\x12.appproto.DashItemR\tdashAudio\"w\n" +
	"\n" +
	"StreamItem\x125\n" +
	"\vstream_info\x18\x01 \x01(\v2\x14.appproto.StreamInfoR\n" +
	"streamInfo\x122\n" +
	"\n" +
	"dash_video\x18\x02 \x01(\v2\x13.appproto.DashVideoR\tdashVideo\"{\n" +
	"\n" +
	"StreamInfo\x12\x18\n" +
	"\aquality\x18\x01 \x01(\rR\aquality\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\berr_code\x18\x04 \x01(\rR\aerrCode\"\xa3\x01\n" +
	"\tDashVideo\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"backup_url\x18\x02 \x03(\tR\tbackupUrl\x12\x1c\n" +
	"\tbandwidth\x18\x03 \x01(\rR\tbandwidth\x12\x18\n" +
	"\acodecid\x18\x04 \x01(\rR\acodecid\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\"\xb2\x01\n" +
	"\bDashItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"backup_url\x18\x03 \x03(\tR\tbackupUrl\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\rR\tbandwidth\x12\x18\n" +
	"\acodecid\x18\x05 \x01(\rR\acodecid\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\x12\x12\n" +
	"\x04size\x18\a \x01(\x04R\x04sizeB;Z9github.com/charleszheng44/bbdown-go/internal/api/appprotob\x06proto3"

var (
	file_internal_api_appproto_playviewreply_proto_rawDescOnce sync.Once
	file_internal_api_appproto_playviewreply_proto_rawDescData []byte
)

func file_internal_api_appproto_playviewreply_proto_rawDescGZIP() []byte {
	file_internal_api_appproto_playviewreply_proto_rawDescOnce.Do(func() {
		file_internal_api_appproto_playviewreply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_appproto_playviewreply_proto_rawDesc), len(file_internal_api_appproto_playviewreply_proto_rawDesc)))
	})
	return file_internal_api_appproto_playviewreply_proto_rawDescData
}

var file_internal_api_appproto_playviewreply_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_api_appproto_playviewreply_proto_goTypes = []any{
	(*PlayViewReply)(nil), // 0: appproto.PlayViewReply
	(*VideoInfo)(nil),     // 1: appproto.VideoInfo
	(*StreamItem)(nil),    // 2: appproto.StreamItem
	(*StreamInfo)(nil),    // 3: appproto.StreamInfo
	(*DashVideo)(nil),     // 4: appproto.DashVideo
	(*DashItem)(nil),      // 5: appproto.DashItem
}
var file_internal_api_appproto_playviewreply_proto_depIdxs = []int32{
	1, // 0: appproto.PlayViewReply.video_info:type_name -> appproto.VideoInfo
	2, // 1: appproto.VideoInfo.stream_list:type_name -> appproto.StreamItem
	5, // 2: appproto.VideoInfo.dash_audio:type_name -> appproto.DashItem
	3, // 3: appproto.StreamItem.stream_info:type_name -> appproto.StreamInfo
	4, // 4: appproto.StreamItem.dash_video:type_name -> appproto.DashVideo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_api_appproto_playviewreply_proto_init() }
func file_internal_api_appproto_playviewreply_proto_init() {
	if File_internal_api_appproto_playviewreply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_appproto_playviewreply_proto_rawDesc), len(file_internal_api_appproto_playviewreply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_appproto_playviewreply_proto_goTypes,
		DependencyIndexes: file_internal_api_appproto_playviewreply_proto_depIdxs,
		MessageInfos:      file_internal_api_appproto_playviewreply_proto_msgTypes,
	}.Build()
	File_internal_api_appproto_playviewreply_proto = out.File
	file_internal_api_appproto_playviewreply_proto_goTypes = nil
	file_internal_api_appproto_playviewreply_proto_depIdxs = nil
}
